---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# *Análisis adicionales encuesta CEPRA-RES*

## *Librerias*

```{r}
library(dplyr)
library(readxl)
library(janitor)
library(ggplot2)
library(forcats)
library(readr)
library(vcd)
library(sf)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 


```

# *Datos*


## *Datos preprocesados*

```{r}

datos <- read_rds("datos_prep/datos_procesados.rds")

unique(datos$city)

diccionario <- readxl::read_excel("datos_prep/diccionario.xlsx", sheet = "diccionario")

glimpse(datos)


```

# *Funciones*

```{r}

simple.table <- function(data=datos,var1){
  t <- mutate(data,"{var1}" := fct_na_value_to_level(!!as.symbol(var1),level="N.A.")
         )|>
  tabyl(!!as.symbol(var1),show_na = T)|>
    # adorn_totals("row")|>
    # adorn_percentages("col")|>
    adorn_pct_formatting(digits=1,rounding = "half to even")|>
  select(!!as.symbol(var1),percent)
 clipr::write_clip(t)
  t
}

my.table <- function(data=datos,cat="city",var1) {
  t.p <- data|>
    tabyl(!!as.symbol(cat),!!as.symbol(var1))|>
    adorn_totals("col")|>
    adorn_percentages("col")|>
    adorn_pct_formatting(digits=1,rounding = "half to even")
  
  t.n <- data|>
    tabyl(!!as.symbol(cat),!!as.symbol(var1))|>
    adorn_totals("col")
  
  t <- t.n
  
  for (i in 2:ncol(t.n)) {
    t[,i] <- paste0(t.n[,i],"(",t.p[,i],")")
    
  }
   clipr::write_clip(t)
   t
}


### Función grafico de barras

barra.g <- function(data=datos,cat="city",var="ida_time"){
  
  data|>
    group_by(!!as.symbol(cat), !!as.symbol(var))|>
    summarise(n=n())|>
    group_by(!!as.symbol(cat))|>
    mutate(pcnt=n/sum(n)*100)|>
    
    ggplot(aes(x=!!as.symbol(var), y=pcnt))+
    geom_col(position = "dodge", fill="gray")+
    geom_text(aes(y=pcnt,label=paste0(round(pcnt,1),"%")),
              position=position_dodge(0.9), 
              vjust=-0.5,
              size=6,
              )+
    facet_wrap(vars(!!as.symbol(cat)),)+
    scale_y_continuous(expand=expansion(mult=c(0,.2)))+
    ylab("%")
    # theme(strip.text = element_text(size=12))
    
}



### Función para mosaic plot
my.mosaic <- function(data, form="ida_time_g1~camina"){
  mosaic(data=data,
        as.formula(form),
        direction = c("v", "h"),
        gp = shading_max,
        spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )
  
}


### Función para guardar gráficos

dir <- "graficos/"

my.ggsave <- function(filename = default_name(plot), 
                      height= 8, 
                      width= 15, 
                      units="cm",
                      dpi= 300, ...){
  ggsave(path = dir,filename=filename, height=height, width=width, dpi=dpi, ...)
}


my.grsave <- function(fname = default_name(plot), 
                      height= 8, 
                      width= 15, 
                      units="cm",
                      dpi= 300, ...){
  png(filename = paste0(dir,fname),
      height=height, 
      width=width, 
      units=units,
      res =dpi
      )
  plot()
}


```

### *Temas*

```{r}


theme_set(theme_minimal(base_size=22))
theme_update(axis.line.x.bottom=element_line(colour = "black"))


```

# *Descriptivo*

```{r}
glimpse(datos)

datos|>
  my.table(cat="city",var1 = "school")

datos|>
  my.table(cat="gender",var1 = "city")

datos|>
  my.table(cat="mode_ida_g1",var1 = "city")

datos|>
  my.table(cat="mode_vuelta_g1",var1 = "city")

datos|>
  my.table(cat="ida_time",var1 = "city")



datos|>
  my.table(cat="ida_bythemself",var1 = "city")

datos|>
  my.table(cat="vuelta_bythemself",var1 = "city")

datos|>
  group_by(city,school,dens_cat)|>
  summarise()|>
  clipr::write_clip()

datos|>
  group_by(city,school,emaps_cat)|>
  summarise()|>
  clipr::write_clip()|>
  print()


```

## *Genero*

```{r}

gender.t <- my.table(cat="city",var1 = "gender")|>
clipr::write_clip()
gender.t



```

## *Modos*

```{r}


mode_ida.t <- my.table(var1 = "mode_ida")
clipr::write_clip(mode_ida.t)
mode_ida.t

mode_vuelta.t <- my.table(var1 = "mode_vuelta")
clipr::write_clip(mode_vuelta.t)
mode_vuelta.t


mode_ida_g1.t <- my.table(var1 = "mode_ida_g1")
clipr::write_clip(mode_ida_g1.t)
mode_ida_g1.t

mode_vuelta_g1.t <- my.table(var1 = "mode_vuelta_g1")
clipr::write_clip(mode_vuelta_g1.t)
mode_vuelta_g1.t

mode_active <- my.table(var1 = "mode_active")
clipr::write_clip(mode_active)
mode_active


mode_vuelta.t <- my.table(var1 = "mode_vuelta")
clipr::write_clip(mode_vuelta.t)
mode_vuelta.t



```

## *Tiempos*

```{r}

ida_tiempo.t <- my.table(var1 = "ida_time")
ida_tiempo.t
clipr::write_clip(ida_tiempo.t)


barra.g(data = datos,cat = "city",var="ida_time")+
  xlab("Travel Time to School (minutes)")+
  theme(panel.grid.major.x = element_blank())



dev.new(width = 15, height = 8, unit="cm", noRStudioGD = T);last_plot()

#my.ggsave("time to shcool.png", width = 15,height = 8, dpi = 300)



# fisher.test(ida_tiempo.t, simulate.p.value=TRUE)


```

## Solo o acompañado

```{r}


barra.g(data = datos,cat = "city",var="ida_bythemself")+
  xlab("Home to Shool by themself")+
  theme(panel.grid.major.x = element_blank())

dev.new(width = 7, height = 5, unit="cm", noRStudioGD = T);last_plot()

##my.ggsave("home to shcool by themself.png", width = 7,height = 5, dpi = 300)


barra.g(data = datos,cat = "city",var="vuelta_bythemself")+
  xlab("School to home by themself")+
  theme(panel.grid.major.x = element_blank())
dev.new(width = 7, height = 5, unit="cm", noRStudioGD = T);last_plot()

#my.ggsave("school to home by themself.png", width = 7,height = 5, dpi = 300)


```

## Beneficios

```{r}

questions <- c(bnfam_academic ="Improves academic performance",
              bnfam_cvrisk="Reduces cardiovascular risk",
              bnfam_obesity ="Prevents obesity",
              bnfam_pollut  ="Reduces pollution",
              bnfam_traffic="Reduces traffic")

questions4l <- c(bnfam4l_academic ="Improves academic performance",
                 bnfam4l_cvrisk="Reduces cardiovascular risk",
                 bnfam4l_obesity ="Prevents obesity",
                 bnfam4l_pollut  ="Reduces pollution",
                 bnfam4l_traffic="Reduces traffic")

d2 <- datos|>
  select(city,bnfam_obesity,bnfam_cvrisk,bnfam_pollut,bnfam_traffic,bnfam_academic)|>
  tidyr::pivot_longer(!city, names_to = "que", values_to = "answ")|>
  group_by(city,que, answ)|>
  summarise(n=n())|>
  mutate(pcnt=n/sum(n)*100,
        answ=fct_na_value_to_level(answ,level="N.A.")
         )
   
  
d2|>  ggplot(aes(y=city, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  facet_wrap(c("que"),ncol =1,
             strip.position="top",
             labeller =labeller(que=questions)
             )+
    scale_fill_manual("",
                    values = c("agree"="gray50",
                               "disagree"="gray75",
                               "N.A."="white"),
                    na.value="white",
                    guide = guide_legend(reverse = T))+
  # labs(labels=c("agree"="gray50","disagree"="gray75","NA"="white"))+
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()

# my.ggsave("benefits.png", width = 5,height = 8, dpi = 300)

#Beneficios por modo
d2modo <- datos|>
  select(city, mode_active,starts_with("bnfam_"))|>
  tidyr::pivot_longer(!c(mode_active,city), names_to = "que", values_to = "answ")|>
  group_by(que,mode_active, answ)|>
  summarise(n=n())|>
  filter(!is.na(answ))|>
  mutate(pcnt=n/sum(n)*100,
        # answ=fct_na_value_to_level(answ,level="N.A.")
         )
   
  
d2modo|>  ggplot(aes(y=mode_active, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black", na.rm = T)+
  geom_vline(xintercept = c(0,25,50,75,100))+
  facet_wrap("que",
             ncol =1,
             strip.position="top",
             labeller =labeller(que=questions)
             )+
  scale_fill_manual("",
                  values = c("agree"="gray40",
                             "disagree"="gray90"),
                  na.value="white",
                  guide = guide_legend(reverse = T))+
  labs(labels=c("agree"="gray50","disagree"="gray75","NA"="white"))+
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()

```

## Razones

```{r}
#razones por modo
d3 <- datos|>
  select(mode_active, mode_ida_g1,
         starts_with("motiv_")
  )|>
  tidyr::pivot_longer(cols = starts_with("motiv_"),
                      names_to = "que",
                      names_prefix = "motiv_",
                      values_to = "answ",
                      values_drop_na = TRUE
                      )|>
  mutate(que=factor(recode(que,
                            distance="Distance",
                            road_safety="Road safety",
                            personal_security="Personal security", 
                            social_relations="Social relations",
                            cost="Cost",
                            healt="Health",
                            convenience="Convenience"
                             )),
         mode_ida_g1=case_match(mode_ida_g1,c("Public bus","School bus")~"Bus",
                                .default =mode_ida_g1
                                )
         )|>
  filter(mode_ida_g1 %in% c("Active","Bus","Private vehicle"))|>
  group_by(mode_ida_g1,que)|>
  summarise(n=sum(as.integer(answ)))|>
  mutate(pcnt=n/sum(n)*100)



d3|>
  # filter(mode_ida_g2=="Active")|>
  ggplot(aes(y=que,x=pcnt))+
  geom_col(fill="gray")+
  geom_vline(xintercept = 0)+
  geom_text(aes(label = paste0(round(pcnt,1),"%")),hjust = -0.05, size=3,
            )+
  xlab(label = "Mode")+
  facet_wrap(~mode_ida_g1)+
  lims(x=c(NA,65))+
  theme(text=element_text(size = 14),
        panel.grid.major.y = element_blank(),
        legend.title = element_blank(),
        axis.title.x = element_text(),
        axis.title.y.left = element_blank(),
        axis.ticks.x = element_line(),
        )

dev.new(width = 12, height =4, unit="cm", noRStudioGD = T);last_plot()

# my.ggsave("reasons.png", width = 15,height = 4, dpi = 300)


#razones por modo activo
d4 <- datos|>
  select(mode_active,
         motiv_distance,
         motiv_road_safety,
         motiv_personal_security,
         motiv_social_relations,
         motiv_cost,
         motiv_health,
         motiv_convenience
  )|>
  tidyr::pivot_longer(cols = starts_with("motiv_"),
                      names_to = "que",
                      names_prefix = "motiv_",
                      values_to = "answ",
                      values_drop_na = TRUE
                      )|>
  mutate(que=factor(recode(que,
                            distance="Distance",
                            road_safety="Road safety",
                            personal_security="Personal security", 
                            social_relations="Social relations",
                            cost="Cost",
                            healt="Health",
                            convenience="Convenience"
                             ))
         )|>
  group_by(mode_active,que)|>
  summarise(n=sum(as.integer(answ)))|>
  mutate(pcnt=n/sum(n)*100)



d4|>
  # filter(mode_ida_g2=="Active")|>
  ggplot(aes(y=que,x=pcnt))+
  geom_col(fill="gray")+
  geom_vline(xintercept = 0)+
  geom_text(aes(label = paste0(round(pcnt,1),"%")),hjust = -0.05, size=3,
            )+
  facet_wrap(~mode_active)+
  lims(x=c(NA,62))+
  theme(text=element_text(size = 14),
        panel.grid.major.y = element_blank(),
        legend.title = element_blank(),
        axis.title.x =  element_blank(),
        axis.title.y.left = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 12, height =4, unit="cm", noRStudioGD = T);last_plot()

# my.ggsave("reasons.png", width = 15,height = 4, dpi = 300)

```

## Concerns

```{r}

questions <- diccionario|>
  filter(grepl("preocupa_",pregunta))|>
  filter(pregunta!="preocupa_om")|>
  select(pregunta,label)
  
#Vector para traducir preguntas
recode_que <- questions$label
names(recode_que) <- questions$pregunta


# #Vector para traducir respuestas
# recode_ans <-c("A lot","Some","Very little","Nothing","N.A.")


d4 <- datos|>
  select(city,mode_ida_g2,
         preocupa_distancia,
         preocupa_trafico,
         preocupa_velocidad,
         preocupa_tiempo,
         preocupa_seguridad_cruces,
         preocupa_falta_policias,
         preocupa_violencia,
         preocupa_frio_calor,
         preocupa_lluvia,
         preocupa_peso,
         preocupa_falta_otros_adultos,
         preocupa_aceras,
         preocupa_falta_otros_ninos,
         preocupa_aburrido_caminar,
         preocupa_falta_otros_adultos_bici,
         preocupa_falta_ciclovias,
         preocupa_falta_lugares_bici,
         preocupa_falta_otrosninos_bici,
         preocupa_aburrido_bici
         )|>
  tidyr::pivot_longer(cols = starts_with("preocupa_"),
                      names_to = "que_o",
                      # names_prefix = "preocupa_",
                      values_to = "answ",
                      values_drop_na = TRUE
                      )|>
  mutate(que = recode(que_o, !!!recode_que)
         )


### ANAlisis por city
d4.city <- d4|>
  group_by(city,que,answ)|>
  summarise(n=n())|>
  mutate(pcnt=n/sum(n)*100)

d4.c <- d4.city|>filter(city=="Cuenca")

pos.c <- d4.c|>filter(answ=="A lot")|>
  arrange(pcnt)
  
d4.c|>mutate(que = factor(que,
                        levels=as.vector(pos.c$que))
             )|>
  ggplot(aes(y=que, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  scale_fill_grey(start = 1,end=0.3)+
  facet_wrap(c("city"),ncol =2,
  #            strip.position="top",
  )+
  guides(fill = guide_legend(reverse = T))+
  theme(panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()
# my.ggsave("concerns_cuenca.png", width = 8,height = 8, dpi = 300)


d4.i <- d4.city|>filter(city=="Ibarra")

pos.i <- d4.i|>filter(answ=="A lot")|>
  arrange(pcnt)
  
d4.i|>mutate(que = factor(que,
                        levels=as.vector(pos.i$que))
             )|>
  ggplot(aes(y=que, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  scale_fill_grey(start = 1,end=0.3)+
  facet_wrap(c("city"),ncol =2,
  #            strip.position="top",
  )+
  guides(fill = guide_legend(reverse = T))+
  theme(panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()
# my.ggsave("concerns_ibarra.png", width = 8,height = 8, dpi = 300)


## Analisis por modo


d4.modo <- d4|>
  group_by(mode_ida_g2,que,answ)|>
  summarise(n=n())|>
  mutate(pcnt=n/sum(n)*100)


d4.ac <- d4.modo|>filter(mode_ida_g2=="Active")

pos.ac <- d4.ac|>filter(answ=="A lot")|>
  arrange(pcnt)

  
d4.ac|>mutate(que = factor(que,
                        levels=as.vector(pos.ac$que))
             )|>
  ggplot(aes(y=que, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  scale_fill_grey(start = 1,end=0.3)+
  facet_wrap(c("mode_ida_g2"),ncol =2,
  #            strip.position="top",
  )+
  guides(fill = guide_legend(reverse = T))+
  theme(panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()
# my.ggsave("concerns_active.png", width = 8,height = 8, dpi = 300)





d4.motor <- d4.modo|>filter(mode_ida_g2=="Motorised")

pos.motor <- d4.motor|>filter(answ=="A lot")|>
  arrange(pcnt)

  
d4.motor|>mutate(que = factor(que,
                        levels=as.vector(pos.motor$que))
             )|>
  ggplot(aes(y=que, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  scale_fill_grey(start = 1,end=0.3)+
  facet_wrap(c("mode_ida_g2"),ncol =2,
  #            strip.position="top",
  )+
  guides(fill = guide_legend(reverse = T))+
  theme(panel.grid.major.x = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()
# my.ggsave("concerns_motorised.png", width = 8,height = 8, dpi = 300)

```


## Improvements

```{r}


questions <- diccionario|>
  filter(grepl("mejoras_",pregunta))|>
  filter(pregunta!="mejoras_om")|>
  select(pregunta,label)
  
#Vector para traducir preguntas
recode_que <- questions$label
names(recode_que) <- questions$pregunta

#Vector para traducir respuestas
recode_ans <-c("Yes","No","N.A.")
names(recode_ans) <- c("Sí","No","No sabe/No contesta")


d5 <- datos|>
  select(city,mode_ida_g2,
         questions$pregunta
         )|>
  tidyr::pivot_longer(cols = questions$pregunta,
                      names_to = "que_o",
                      values_to = "answ_o",
                      values_drop_na = TRUE
                      )|>
  mutate(que = recode(que_o, !!!recode_que),
         answ = recode(answ_o, !!!recode_ans),
         answ = fct_relevel(answ,recode_ans)
         )

#Por city
d5.city <- d5|>
  group_by(city,que,answ)|>
  summarise(n=n())|>
  mutate(pcnt=n/sum(n)*100)

 
d5.city|>  ggplot(aes(y=city, x=pcnt, fill=forcats::fct_rev(answ)))+
  geom_col(col="black")+
  geom_vline(xintercept = c(0,25,50,75,100))+
  scale_fill_grey(start = 1,end =0.3 )+
  facet_wrap(c("que"),ncol =2,
             strip.position="top",
             # labeller =labeller(questions$label)
             )+
  guides(fill = guide_legend(reverse = T))+
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_line()
        )

dev.new(width = 8, height =8, unit="cm", noRStudioGD = T);last_plot()
# my.ggsave("improvement_city.png", width = 8,height = 8, dpi = 300)

```


# *Asociaciones*


```{r}

set.seed(1977)

#gender
d1 <- datos|>  
  filter(!is.na(gender))|>
  droplevels()

form=~gender+mode_active


mosaic(data=d1,form,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )



#Mode by cities.
d1 <- datos
form=~mode_active+city
mosaic(data=d1,form,
        gp = shading_hcl,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )
 

 
#Mode by time
d1 <- datos|>
  filter(!is.na(ida_time_g1))|>
  rename("Travel_time"=ida_time_g1)|>
  droplevels()

form=~mode_active+Travel_time
mosaic(data=d1,form,
        gp = shading_hcl,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )



#Mode by time
d1 <- datos|>
  filter(!is.na(ida_time_g1))|>
  rename("Travel_time"=ida_time_g1)|>
  droplevels()

form=~mode_active+Travel_time
mosaic(data=d1,form,
        gp = shading_hcl,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )




#Mode by socioeconomic
d1 <- datos|>
  filter(!is.na(parent_studies))|>
  # rename("Travel_time"=ida_time_g1)|>
  droplevels()

form=~mode_active+parent_studies
mosaic(data=d1,form,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )


d1 <- datos|>
  filter(!is.na(family_vehicle))|>
  # rename("Travel_time"=ida_time_g1)|>
  droplevels()

form=~mode_active+family_vehicle
mosaic(data=d1,form,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )

d1 <- datos|>
  filter(!is.na(household_income))|>
  droplevels()

form=~mode_active+household_income
mosaic(data=d1,form,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )



```


```{r}


d1 <- datos|>
  filter(!is.na(household_income),
         !is.na(family_vehicle))|>
  droplevels()

form=~family_vehicle+household_income

mosaic(data=d1,form,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )



```

```{r landuse}


mosaic(data=datos,~dens_cat+mode_active,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )


mosaic(data=datos,~emaps_cat+mode_active,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )



mosaic(data=datos,~emaps_cat+dens_cat,
        gp = shading_max,
       spacing = vcd::spacing_equal(sp = unit(0.4, "lines"))
        )

```

